{"text": "2021-07-09T08:15:34.336639+0000 ERROR An error has been caught in function 'dispatch', process 'MainProcess' (800), thread 'ThreadPoolExecutor-0_0' (140524481648384):\nTraceback (most recent call last):\n\n  File \"/usr/local/lib/python3.8/threading.py\", line 890, in _bootstrap\n    self._bootstrap_inner()\n    \u2502    \u2514 <function Thread._bootstrap_inner at 0x7fce72160e50>\n    \u2514 <Thread(ThreadPoolExecutor-0_0, started daemon 140524481648384)>\n  File \"/usr/local/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n    self.run()\n    \u2502    \u2514 <function Thread.run at 0x7fce72160b80>\n    \u2514 <Thread(ThreadPoolExecutor-0_0, started daemon 140524481648384)>\n  File \"/usr/local/lib/python3.8/threading.py\", line 870, in run\n    self._target(*self._args, **self._kwargs)\n    \u2502    \u2502        \u2502    \u2502        \u2502    \u2514 {}\n    \u2502    \u2502        \u2502    \u2502        \u2514 <Thread(ThreadPoolExecutor-0_0, started daemon 140524481648384)>\n    \u2502    \u2502        \u2502    \u2514 (<weakref at 0x7fce67dc2cc0; to 'ThreadPoolExecutor' at 0x7fce720e5280>, <_queue.SimpleQueue object at 0x7fce72106450>, None,...\n    \u2502    \u2502        \u2514 <Thread(ThreadPoolExecutor-0_0, started daemon 140524481648384)>\n    \u2502    \u2514 <function _worker at 0x7fce720efaf0>\n    \u2514 <Thread(ThreadPoolExecutor-0_0, started daemon 140524481648384)>\n  File \"/usr/local/lib/python3.8/concurrent/futures/thread.py\", line 80, in _worker\n    work_item.run()\n    \u2502         \u2514 <function _WorkItem.run at 0x7fce720efc10>\n    \u2514 <concurrent.futures.thread._WorkItem object at 0x7fce66a13a00>\n  File \"/usr/local/lib/python3.8/concurrent/futures/thread.py\", line 57, in run\n    result = self.fn(*self.args, **self.kwargs)\n             \u2502    \u2502   \u2502    \u2502       \u2502    \u2514 {}\n             \u2502    \u2502   \u2502    \u2502       \u2514 <concurrent.futures.thread._WorkItem object at 0x7fce66a13a00>\n             \u2502    \u2502   \u2502    \u2514 []\n             \u2502    \u2502   \u2514 <concurrent.futures.thread._WorkItem object at 0x7fce66a13a00>\n             \u2502    \u2514 functools.partial(<bound method SyncToAsync.thread_handler of <asgiref.sync.SyncToAsync object at 0x7fce6d38e640>>, <_UnixSel...\n             \u2514 <concurrent.futures.thread._WorkItem object at 0x7fce66a13a00>\n  File \"/usr/local/lib/python3.8/site-packages/asgiref/sync.py\", line 462, in thread_handler\n    return func(*args, **kwargs)\n           \u2502     \u2502       \u2514 {}\n           \u2502     \u2514 (functools.partial(<function convert_exception_to_response.<locals>.inner at 0x7fce6d3911f0>, <ASGIRequest: POST '/api/ad/cre...\n           \u2514 <built-in method run of Context object at 0x7fce6d3c0480>\n  File \"/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py\", line 47, in inner\n    response = get_response(request)\n               \u2502            \u2514 <ASGIRequest: POST '/api/ad/create'>\n               \u2514 <debug_toolbar.middleware.DebugToolbarMiddleware object at 0x7fce6d38e5b0>\n  File \"/usr/local/lib/python3.8/site-packages/debug_toolbar/middleware.py\", line 48, in __call__\n    return self.get_response(request)\n           \u2502    \u2502            \u2514 <ASGIRequest: POST '/api/ad/create'>\n           \u2502    \u2514 <function convert_exception_to_response.<locals>.inner at 0x7fce6d38aaf0>\n           \u2514 <debug_toolbar.middleware.DebugToolbarMiddleware object at 0x7fce6d38e5b0>\n  File \"/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py\", line 47, in inner\n    response = get_response(request)\n               \u2502            \u2514 <ASGIRequest: POST '/api/ad/create'>\n               \u2514 <debug_toolbar_force.middleware.ForceDebugToolbarMiddleware object at 0x7fce6d38e370>\n  File \"/usr/local/lib/python3.8/site-packages/debug_toolbar_force/middleware.py\", line 30, in __call__\n    response = self.get_response(request)\n               \u2502    \u2502            \u2514 <ASGIRequest: POST '/api/ad/create'>\n               \u2502    \u2514 <asgiref.sync.AsyncToSync object at 0x7fce6d389ac0>\n               \u2514 <debug_toolbar_force.middleware.ForceDebugToolbarMiddleware object at 0x7fce6d38e370>\n  File \"/usr/local/lib/python3.8/site-packages/asgiref/sync.py\", line 201, in __call__\n    current_executor.run_until_future(loop_future)\n    \u2502                \u2502                \u2514 <Future at 0x7fce66cbaf10 state=running>\n    \u2502                \u2514 <function CurrentThreadExecutor.run_until_future at 0x7fce720ee1f0>\n    \u2514 <asgiref.current_thread_executor.CurrentThreadExecutor object at 0x7fce66cba040>\n  File \"/usr/local/lib/python3.8/site-packages/asgiref/current_thread_executor.py\", line 62, in run_until_future\n    work_item.run()\n    \u2502         \u2514 <function _WorkItem.run at 0x7fce720ee0d0>\n    \u2514 <asgiref.current_thread_executor._WorkItem object at 0x7fce66cb9310>\n  File \"/usr/local/lib/python3.8/site-packages/asgiref/current_thread_executor.py\", line 22, in run\n    result = self.fn(*self.args, **self.kwargs)\n             \u2502    \u2502   \u2502    \u2502       \u2502    \u2514 {}\n             \u2502    \u2502   \u2502    \u2502       \u2514 <asgiref.current_thread_executor._WorkItem object at 0x7fce66cb9310>\n             \u2502    \u2502   \u2502    \u2514 ()\n             \u2502    \u2502   \u2514 <asgiref.current_thread_executor._WorkItem object at 0x7fce66cb9310>\n             \u2502    \u2514 functools.partial(<bound method SyncToAsync.thread_handler of <asgiref.sync.SyncToAsync object at 0x7fce66cb9af0>>, <_UnixSel...\n             \u2514 <asgiref.current_thread_executor._WorkItem object at 0x7fce66cb9310>\n  File \"/usr/local/lib/python3.8/site-packages/asgiref/sync.py\", line 462, in thread_handler\n    return func(*args, **kwargs)\n           \u2502     \u2502       \u2514 {}\n           \u2502     \u2514 (functools.partial(<function AdCreateView at 0x7fce6d434430>, <ASGIRequest: POST '/api/ad/create'>),)\n           \u2514 <built-in method run of Context object at 0x7fce65de7340>\n  File \"/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py\", line 54, in wrapped_view\n    return view_func(*args, **kwargs)\n           \u2502          \u2502       \u2514 {}\n           \u2502          \u2514 (<ASGIRequest: POST '/api/ad/create'>,)\n           \u2514 <function AdCreateView at 0x7fce6d4343a0>\n  File \"/usr/local/lib/python3.8/site-packages/django/views/generic/base.py\", line 70, in view\n    return self.dispatch(request, *args, **kwargs)\n           \u2502    \u2502        \u2502         \u2502       \u2514 {}\n           \u2502    \u2502        \u2502         \u2514 ()\n           \u2502    \u2502        \u2514 <ASGIRequest: POST '/api/ad/create'>\n           \u2502    \u2514 <function APIView.dispatch at 0x7fce70d64040>\n           \u2514 <ad.views.AdCreateView object at 0x7fce66cb98e0>\n> File \"/usr/local/lib/python3.8/site-packages/rest_framework/views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               \u2502       \u2502         \u2502       \u2514 {}\n               \u2502       \u2502         \u2514 ()\n               \u2502       \u2514 <rest_framework.request.Request: POST '/api/ad/create'>\n               \u2514 <bound method AdCreateView.post of <ad.views.AdCreateView object at 0x7fce66cb98e0>>\n\n  File \"/usr/src/Backend_DRF_v2/ad/views.py\", line 56, in post\n    ad = author_ad.create(\n         \u2502         \u2514 <function QuerySet.create at 0x7fce71212ca0>\n         \u2514 <QuerySet []>\n\n  File \"/usr/local/lib/python3.8/site-packages/django/db/models/query.py\", line 453, in create\n    obj.save(force_insert=True, using=self.db)\n    \u2502   \u2502                             \u2502    \u2514 <property object at 0x7fce7120b8b0>\n    \u2502   \u2502                             \u2514 <QuerySet []>\n    \u2502   \u2514 <function Model.save at 0x7fce710fdd30>\n    \u2514 <Ad: \u041e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0435 alexnovpac>\n  File \"/usr/local/lib/python3.8/site-packages/django/db/models/base.py\", line 726, in save\n    self.save_base(using=using, force_insert=force_insert,\n    \u2502    \u2502               \u2502                   \u2514 True\n    \u2502    \u2502               \u2514 'default'\n    \u2502    \u2514 <function Model.save_base at 0x7fce710fddc0>\n    \u2514 <Ad: \u041e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0435 alexnovpac>\n  File \"/usr/local/lib/python3.8/site-packages/django/db/models/base.py\", line 750, in save_base\n    pre_save.send(\n    \u2502        \u2514 <function Signal.send at 0x7fce72237e50>\n    \u2514 <django.db.models.signals.ModelSignal object at 0x7fce715d3ee0>\n  File \"/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py\", line 180, in send\n    return [\n  File \"/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py\", line 181, in <listcomp>\n    (receiver, receiver(signal=self, sender=sender, **named))\n     \u2502         \u2502               \u2502            \u2502         \u2514 {'instance': <Ad: \u041e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0435 alexnovpac>, 'raw': False, 'using': 'default', 'update_fields': None}\n     \u2502         \u2502               \u2502            \u2514 <class 'ad.models.Ad'>\n     \u2502         \u2502               \u2514 <django.db.models.signals.ModelSignal object at 0x7fce715d3ee0>\n     \u2502         \u2514 <function on_change at 0x7fce6eaaa9d0>\n     \u2514 <function on_change at 0x7fce6eaaa9d0>\n\n  File \"/usr/src/Backend_DRF_v2/ad/models.py\", line 59, in on_change\n    async_to_sync(channel_layer.group_send)(\n    \u2502             \u2502             \u2514 <function RedisChannelLayer.group_send at 0x7fce669bd310>\n    \u2502             \u2514 <channels_redis.core.RedisChannelLayer object at 0x7fce70ea00d0>\n    \u2514 <class 'asgiref.sync.AsyncToSync'>\n\n  File \"/usr/local/lib/python3.8/site-packages/asgiref/sync.py\", line 222, in __call__\n    return call_result.result()\n           \u2502           \u2514 <function Future.result at 0x7fce725aae50>\n           \u2514 <Future at 0x7fce669e9280 state=finished raised TypeError>\n  File \"/usr/local/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n    return self.__get_result()\n           \u2514 None\n  File \"/usr/local/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n    raise self._exception\n          \u2514 None\n  File \"/usr/local/lib/python3.8/site-packages/asgiref/sync.py\", line 287, in main_wrap\n    result = await self.awaitable(*args, **kwargs)\n                   \u2502    \u2502          \u2502       \u2514 {}\n                   \u2502    \u2502          \u2514 (<class 'ad.consumers.AdConsumer'>, {'type': 'ad.ad', 'event': 'New Ad', 'username': 'alexnovpac'})\n                   \u2502    \u2514 <bound method RedisChannelLayer.group_send of <channels_redis.core.RedisChannelLayer object at 0x7fce70ea00d0>>\n                   \u2514 <asgiref.sync.AsyncToSync object at 0x7fce669e9400>\n  File \"/usr/local/lib/python3.8/site-packages/channels_redis/core.py\", line 667, in group_send\n    assert self.valid_group_name(group), \"Group name not valid\"\n           \u2502    \u2502                \u2514 <class 'ad.consumers.AdConsumer'>\n           \u2502    \u2514 <function BaseChannelLayer.valid_group_name at 0x7fce6e9f6c10>\n           \u2514 <channels_redis.core.RedisChannelLayer object at 0x7fce70ea00d0>\n  File \"/usr/local/lib/python3.8/site-packages/channels/layers.py\", line 165, in valid_group_name\n    raise TypeError(\n\nTypeError: Group name must be a valid unicode string containing only ASCII alphanumerics, hyphens, or periods.\n", "record": {"elapsed": {"repr": "0:00:08.171144", "seconds": 8.171144}, "exception": {"type": "TypeError", "value": "Group name must be a valid unicode string containing only ASCII alphanumerics, hyphens, or periods.", "traceback": true}, "extra": {}, "file": {"name": "views.py", "path": "/usr/local/lib/python3.8/site-packages/rest_framework/views.py"}, "function": "dispatch", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 506, "message": "An error has been caught in function 'dispatch', process 'MainProcess' (800), thread 'ThreadPoolExecutor-0_0' (140524481648384):", "module": "views", "name": "rest_framework.views", "process": {"id": 800, "name": "MainProcess"}, "thread": {"id": 140524481648384, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2021-07-09 08:15:34.336639+00:00", "timestamp": 1625818534.336639}}}
